### ISSUE TITLE
add a issue and PR templates

### ISSUE THREAD

**Issue by abhi18av** [nextflow-hub/nextflow_hub_process#2]
@sharma-shruti we need to design the PR and Issue templates - here's a starting point 
https://tommcfarlin.com/github-pr-templates/

And here are some sample templates

https://github.com/samccone/issue-and-pr-templates

https://github.com/echobind/pr-templates/blob/master/oss/PULL_REQUEST_TEMPLATE

https://github.com/stevemao/github-issue-templates/

**Comment by sharma-shruti** [comment]
This seems like a good idea. 
1. I remember creating my very first issue for `doctl`. So when I clicked on `New issue`, it asked whether this issue is a bug or an enhancement request. 
2. We could do something similar. I wonder if the biologists may have some other requirements.
3. An `Issue template` can include:
- A clear and concise description of the problem.
- Software or application environment info.
4. I think for creating a PR request, we first need to have an open issue. We can discuss this later.

**Comment by abhi18av** [comment]
Cool, please lead the way here 🙂
________________________________

**Comment by abhi18av** [comment]
@sharma-shruti , has initiated efforts in the `fastqc` repo. However, we need to implement and test them here in this repo first.

https://github.com/nextflow-hub/fastqc/pull/2

**Comment by abhi18av** [comment]
And the PR related work has been initiated https://github.com/nextflow-hub/fastqc/pull/3 as well. 

@sharma-shruti , please read the above comments for testing out this feature in this repo first :)

**Comment by sharma-shruti** [comment]
Oh sorry. I will work on this repo for template creation.

**Comment by abhi18av** [comment]
@sharma-shruti , try creating a new issue - you'll see your PR at work!

**Comment by abhi18av** [comment]
The PR template is still WIP

**Comment by abhi18av** [comment]
Both the PRs have been merged. Thanks for taking out the time for this @sharma-shruti !
